# Feloowship_AI_Challenge

GitHub did not allow to upload the datasets, as it was too large.
